// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmrhtymnwnfohqseiqtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtcmh0eW1ud25mb2hxc2VpcXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjI5NTksImV4cCI6MjA2MzMzODk1OX0.NqIeJej0z1v_eRqF1kZL5XEpgC-ZM9-pmcQWTgUdiZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);